sudo: false

cache:
  directories:
    - ~/.m2/repository

language: java
jdk:
  - oraclejdk8

install:
  - mvn --settings .travis/mvnsettings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: CurrencyFair/OneSignal-Java-SDK
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: CurrencyFair/OneSignal-Java-SDK
      tags: true
      jdk: oraclejdk8

after_deploy:
  - .travis/after_deploy.sh

notifications:
  slack:
    rooms:
      - secure: "VlqeD7HK9kDHeYTcqNZoGTD3H8a6qIrDBWXXxQ5w62jczFcCLUJozDRN1xqtmsOvRANQdEO7NzPwM+viOLIEU1vdgLk27Fx8yxzKYMlfScwT+NFLeK9Z8l5ZTbPB0mH1TnY1VqSdKX0JZo0RBYz1IKprWEXmnzwZEXXzufS4On8hxyn29r55x3kasCU1HCyAUmiL/qRde7Q3oqIl1sUbKfTgbO4OzuR75zUfDQt3NTmVc/HkVKhtj7xNxHkdy9ERNKY1YNGG4hVUTcjaUn3NSpIFP1zw5Bz05Im2dIuc9S6cmnCeT/ee3JKaC02x/Ra5TbJKWZB3u4ZOZ/i++R+u7Ku6csncbsZPANJE1Kqcgw9FazCxejMp1xhF1Nqqsw6tXwQWyrxyXVk2a+dhejn5d/AJAWVGeAYbpQmdeFMdabUcfSlfPU8CLOO9c1EliN1R9oBaijhhwcC8OauS/1/GIOvhu5PjxZ32szRA3jk5ijdGfZKA8OPUMBfF1CcU5cwT/CEk2WGYzHlx0we+DJBbbZehQ1bqIo6pW6LYeO/0CyKm0FO/jT8C71BNf1rgQa//4z6opjYexSkmuC9IV2Kk4x28vOzW9No7dN5QPytXp3mp0/QYO2egi3c3BjOH0fB/QY17EVad0820RdyH1wSxmC8CnPJkemK9nY/ZEn/8ulI="
    on_success: always
    on_failure: always
  email:
    recipients:
      - tech@currencyfair.com
    on_success: change
    on_failure: always

env:
  global:
    - GIT_NAME="Mateusz Bajorek"
    - GIT_EMAIL="mateusz.bajorek@gmail.com"
