sudo: false

cache:
  directories:
    - ~/.m2/repository

language: java
jdk:
  - oraclejdk8

install:
  - mvn --settings .travis/mvnsettings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: CurrencyFair/OneSignal-Java-SDK
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: CurrencyFair/OneSignal-Java-SDK
      tags: true
      jdk: oraclejdk8

notifications:
  slack:
    secure: "DpNAA/yc3b2J3d916wGj0MYiia8mecFDMMP5U8R2vaRHaCNkQmbTBhF6oCCFUrL+d6hH0lpb4xKDqEiZ2wM5gMznZVTMEeCw2bD1ika2uYdX2GyU0qzfEgiAU4LPyl1fBTtrweQ4D9yTtFTrijV63mG3Nq2XVRm/+9sNhZ/j8ZaudBttsWrIdNSsCyY6pKQLyBLUVWj7H6+1hybbKw6iipOyKsHBVOhl9BOSXXbPz4FZbZ5RuEVZ1aUmc8+Ygd7xxQZUVpGY23UlwaTUUpufds9XzjVZ8JyebbymcK6p7LJwZEAEy2YnNMVDMM8jndyS23soNiRpdxEutSlcHBM10kIeYfDmecq0VnyCBoswtppe6otKcov3isoMEcqMmYD3de9WALQghXOeKLi8Y9Jd7KRIUr3hL0bcAHpawboZxFqqNSJTxb9+plD6EeZCBYVf/49zYrDDBysqHzAALvjAEN4mOHIIiDmzPuyzQCmsSWCDK9hf1HztWn6HDoq2HTsGQGLBZYMC4ZM+kenj3I0BLjW9buQnFCafUV4WzYx36lyXjhJgje323nOM7Ym31gfLK29slnODwaUWL3O/c2hLwdiUbKEX8merzN3NTRruHQgdHgLNPVWmYi4rIOJHJVrSLY0ArquX/DGQjIsMbG3dxkkoxCpWYsbzaXb6hsTWow0="
    on_success: change
    on_failure: always
  email:
    recipients:
      - tech@currencyfair.com
    on_success: change
    on_failure: always
