sudo: false

cache:
  directories:
  - "$HOME/.m2"

language: java

jdk:
  - oraclejdk8

notifications:
  slack:
    secure: DpNAA/yc3b2J3d916wGj0MYiia8mecFDMMP5U8R2vaRHaCNkQmbTBhF6oCCFUrL+d6hH0lpb4xKDqEiZ2wM5gMznZVTMEeCw2bD1ika2uYdX2GyU0qzfEgiAU4LPyl1fBTtrweQ4D9yTtFTrijV63mG3Nq2XVRm/+9sNhZ/j8ZaudBttsWrIdNSsCyY6pKQLyBLUVWj7H6+1hybbKw6iipOyKsHBVOhl9BOSXXbPz4FZbZ5RuEVZ1aUmc8+Ygd7xxQZUVpGY23UlwaTUUpufds9XzjVZ8JyebbymcK6p7LJwZEAEy2YnNMVDMM8jndyS23soNiRpdxEutSlcHBM10kIeYfDmecq0VnyCBoswtppe6otKcov3isoMEcqMmYD3de9WALQghXOeKLi8Y9Jd7KRIUr3hL0bcAHpawboZxFqqNSJTxb9+plD6EeZCBYVf/49zYrDDBysqHzAALvjAEN4mOHIIiDmzPuyzQCmsSWCDK9hf1HztWn6HDoq2HTsGQGLBZYMC4ZM+kenj3I0BLjW9buQnFCafUV4WzYx36lyXjhJgje323nOM7Ym31gfLK29slnODwaUWL3O/c2hLwdiUbKEX8merzN3NTRruHQgdHgLNPVWmYi4rIOJHJVrSLY0ArquX/DGQjIsMbG3dxkkoxCpWYsbzaXb6hsTWow0=
    on_success: change
    on_failure: always
  email:
    recipients:
      - tech@currencyfair.com
    on_success: change
    on_failure: always

env:
  global:
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_username --add
  - secure: UdFsmrAHMJzTND6P7omOByXDmW+qRATl1Kr6oXXrPfdekMtpLgZZpk65gYTF7tpL2ITKc/Kz6WEU0kAkFGAlhaQQCPyjW8TdzxUCs5TtidlbA5cG/Fofn0K3zP5/j7s4QLCLcX8pqv4OG0EDxQbKHH/yTaWLxgHF+ffPwqAhDJXyFYxujqoMjg5XnRIrwmJxzUSyYehWYeAEBCUBnCq3HBX1J7lCR+laD6KI5oXoEHU2XMYWZHcNeduGm2jG2fueI2otP1Qyn1mmEUjnzNeWax8SNOQtRzMWnIZ3enqcUfBpNp/CudaU3tzTP0Xxp+eYMLp/EbgW+7R2KpIjF43g11fwhG9pCLZedJUkL4u2EhVsc80vs5InPFPFk7B4xuD5VQVj9HYKVFqV9F9lx6uEMe3/XOatsGbO4nXp7iCjOGdwo8GYfTRkoa9ICtWfxmPGl4IYCvyG8czZTFFpYAxAG0CMpOrj6MBesW2Xm8cK4/zewuU+YM/T3pLi7im7x58I76fKpt2lQ0doSZK6NXr5MUntHJOanVOT+k3TKZoFySHefsV/zVVE2Mao6P8ui/PC7oJJLdhSGQkT/g97dP6HWyF1SiSJiP2LIhN8Aw+7YfGo+M/RAC8tQwWDLwZVplVrCTiYKDaPMFt38nbwzESXgYYtwm1sH//bE2gNe11fZrA=
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password --add
  - secure: inMzoLUpg5igKAE06WC31NLDBomI7SguPJmYKaH1DRaz7fwIcqOESVUOcG/MSBhHFvPFD6P+mtWwQrbbLUNFBR6zPxh7N0y/pBMhavUqxLaomwrPWeDYubOP7mRv/HdVKjU5R4bl2Bt2UoEkLI2GwgBxGbWjN+KHzWwmSM4X/fmxdSPiulIYRGSXNzKbdBgWZeQCIgjGrnyuNlWevpDKuoD4OIYobeNkrTAUCzK8K7B7TfVXsiQ76htvHNNr16+G4qnm4TTWrdnD1CxsEICmMuJ1vBuyp1KaTUCqbNaOhwZO3VMU9R+1mq3PBTt9OwbG/VrOcrYtDGdt7AooH73Xm/pVolJrgpv3Ux2dE5S9i+HITJws2hy7o7+EZDTnLLxLpsOUzKx+NTDLugZpiTfTqPtjjJIjLyoEnciQoSmgnE9UiPXEng4O2jN12wTZw2qYvSGeUxbSis2EvBEyYs3ohzPd9Zjo69DvgFyTcR5D4C0QLO4GnNtqoHySn39UPkOioetuuYJjdFw7uy0OvacMOINveqGzmiYAD5SGPwbP3Icu8HlykH4eGtBmre2Ey2YODyDjbR1fErPS5ihRRNpxpAtlz4g8EWZ4lQicBbrVAWfZXJWX1b0z7KQFd1DkERBH71oztP9ak6zrMemRHW97tt0t30Et9HWoo9BmQ/sIP7M=
